node{
    stage("Checkoutcode"){
        
        git credentialsId: 'git-credentials', url: 'https://github.com/podilaprudhvi/EmployeeProjReactjs.git'
    }
    stage("Build"){
        
      nodejs(nodeJSInstallationName: "nodejs15.3.0"){
          sh "npm install"
      }  
    }